### ISSUE TITLE
[ui] wire up verify email and clean up auth ux

### ISSUE THREAD

**Issue by harryhexhash** [opencorelabs/fira#47]

**Comment by pnwx** [comment]
Verify email will now include a link as of https://github.com/opencorelabs/fira/pull/51

**Comment by harryhexhash** [comment]
Thanks for the update! Starting on implementing now

**Comment by harryhexhash** [comment]
https://github.com/opencorelabs/fira/assets/129999410/4c9bf1c4-974e-40a2-862e-f7ac983114f5
