### ISSUE TITLE
Add Github updates stream to Discord

### ISSUE THREAD

**Issue by m3tablock** [opencorelabs/fira#50]
Add Github update stream to "github-updates" channel in Discord

 Discord link: https://discord.gg/uGFwMGDGku

**Comment by pnwx** [comment]
<img width="614" alt="Screenshot 2023-05-21 at 12 34 14 PM" src="https://github.com/opencorelabs/fira/assets/132782902/dede16f5-d3b3-40d8-ba41-29ba73be8541">

Done
